baseURL = 'https://xautjzd.github.io/'
languageCode = 'zh-cn'
title = 'Zhengdong.jzd 个人博客'
theme = 'archie'
copyright = "© jzd"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# paginate=3 # articles per page

[services]
  [services.googleAnalytics]
    id = "G-MD311WEJXY"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/xautjzd"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/xautjzd/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
